--DROP TABLE IF EXISTS USR.USER;

--DROP SCHEMA IF EXISTS USR;

CREATE SCHEMA USR;

CREATE TABLE USR.USER (
  USER_ID BIGSERIAL NOT NULL,
  NAME VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);

